apiVersion: v1
kind: Pod
metadata:
  name: myapp-with-init
spec:
  initContainers:
    - name: wait-for-db
      image: busybox
      command: ["sh", "-c", "until nc -z mysql 3306; do sleep 1; done;"]
  containers:
    - name: main-app
      image: nginx:latest
      ports:
        - containerPort: 8080

