apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: wordpress
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      component: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: wordpress
        component: mysql
    spec:
      containers:
      - image: mysql:oracle
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: standard
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: wordpress
    component: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    component: mysql
  clusterIP: 
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app: wordpress
    component: mysql
type: Opaque
data:
  password: c3VwZXJzZWNyZXRwYXNzd29yZA==
  # supersecretpassword% 

