apiVersion: v1
kind: Pod
metadata:
  name: seccomp-pod
spec:
  containers:
  - name: seccomp-container
    image: my-container
    securityContext:
      seccompProfile:
        type: RuntimeDefault

