apiVersion: v1
kind: Pod
metadata:
 name: security-context-demo-2
spec:
 securityContext:
   runAsUser: 1000
 containers:
 - name: sec-ctx-demo-2
   image: busybox:1.28
   command: [ "sh", "-c", "sleep 1h" ]
   securityContext:
     runAsUser: 2000
     allowPrivilegeEscalation: false

