apiVersion: v1
kind: Pod
metadata:
  name: security-context-example
spec:
  containers:
  - image: busybox
    name: busybox
    args:
    - sleep
    - "3600"
    securityContext:
      privileged: true

