apiVersion: v1
kind: Pod
metadata:
  name: pod-with-ambassador-pattern
  labels:
    app: main
spec:
  containers:
  - name: main-container
    image: httpd
    ports:
    - containerPort: 80
  - name: proxy-container
    image: nginx:latest
    ports:
    - containerPort: 8080
    env:
    - name: MAIN_HOST
      value: "localhost"
    - name: MAIN_PORT
      value: "80"
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8080;
        location / {
          proxy_pass http://localhost:80;
        }
      }
    }

