apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: green 
  name: blue 
  namespace: ckad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - image: nginx
        name: nginx
