apiVersion: v1
kind: Pod
metadata:
  name: myapp-with-sidecar
spec:
  containers:
    - name: main-app
      image: nginx:latest
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
      ports:
        - containerPort: 8080
    - name: fluentd
      image: fluent/fluentd:edge-debian
      volumeMounts:
        - name: logs
          mountPath: /var/log/nginx
  volumes:
    - name: logs
      hostPath:
        path: /var/log

