apiVersion: v1
kind: ConfigMap
metadata:
  name: log-config
data:
  username: k8s-admin
  access_level: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test
      image: busybox:1.28
      command: ['sh', '-c', 'echo "The app is running!" && tail -f /dev/null']
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  volumes:
    - name: config-vol
      configMap:
        name: log-config
        #items:
        #  - key: username 
        #    path: keys 
         # - key: access_level
         #   path: keys
#https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

