apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
spec:
  replicas: 1  # Initially set to 0 replicas until switch
  selector:
    matchLabels:
      app: my-app
      version: green
  template:
    metadata:
      labels:
        app: my-app
        version: green
    spec:
      containers:
        - name: my-app
          image: nginx 
          ports:
            - containerPort: 80

