apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
    version: green  # Switch traffic to green version
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
