apiVersion: v1
kind: Pod
metadata:
  name: annotated-pod
  annotations:
    description: "This is a pod with annotations"
    created-by: "user@example.com"
spec:
  containers:
    - name: nginx
      image: nginx:latest

