apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4=    # Base64 encoded string for 'admin'
  password: c2VjcmV0cGFzc3dvcmQ=    # Base64 encoded string for 'secretpassword'

