apiVersion: apps/v1
kind: Deployment
metadata:
  name: combine-readiness-liveness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: both
  template:
    metadata:
      labels:
        app: both
    spec:
      containers:
      - name: both-container
        image: nginx:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
