apiVersion: v1
kind: Pod
metadata:
  name: readiness-httpget
spec:
  containers:
  - name: readiness-httpget
    image: nginx:latest
    readinessProbe:
      httpGet:
        path: /error.html
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
